config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Root path
  root 'root#index'

  # Devise
  devise_for :users

  # Resources
  resources :accounts, except: [ :new, :edit ], defaults: { format: 'json' }

  namespace :account do
    resources :prefixes, except: [ :new, :edit], defaults: { format: 'json' }
    resources :transactions, except: [ :new, :edit], defaults: { format: 'json' }
  end

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :debits,
    class_name: 'Account::Transaction',
    foreign_key: 'debit_account_id'

  has_many :credits,
    class_name: 'Account::Transaction',
    foreign_key: 'credit_account_id'

  belongs_to :prefix,
    class_name: 'Account::Prefix',
    foreign_key: 'account_prefix_id'

  validates :number,
    presence: true,
    numericality: { greater_than: 0 }

  validates :value,
    presence: true

  def name
    "#{prefix}-#{number}"
  end

  alias_method :to_s, :name

  def transaction_changed
    update(value: debits.sum(:value) - credits.sum(:value))
  end

end

app/models/account/prefix.rb
class Account::Prefix < ActiveRecord::Base

  has_many :accounts,
    foreign_key: 'account_prefix_id',
    as: 'prefix'

  validates :name,
    presence: true

  def to_s
    name
  end

  before_save -> { self.name = self.name.upcase }

end

app/models/account/transaction.rb
class Account::Transaction < ActiveRecord::Base

  belongs_to :credit,
    class_name: 'Account',
    foreign_key: 'credit_account_id'

  belongs_to :debit,
    class_name: 'Account',
    foreign_key: 'debit_account_id'

  validates :value,
    presence: true

  after_save -> { [credit, debit].each { |a| a.transaction_changed }}
  
end

app/models/pot.rb
class Pot < ActiveRecord::Base

  #####################
  ### Pot           ###
  #####################
  ### bag:    Bag   ###
  ### plants: Plant ###
  ### lot:    Lot   ###
  #####################



  ### Bag

  belongs_to :bag



  ### Plants

  has_many :plants, through: :bag



  ### Lot

  def lot
    bag.lot
  end

  def lot=(lot)
    bag.lot = lot
  end

  def to_s
    "#{ name.titleize unless name.nil? }"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waste.rb
class Waste < ActiveRecord::Base

  has_many :incoming_transactions, as: 'source'

  def incoming_weight
    incoming_transactions.sum(:weight)
  end

  def to_s
    'Waste'
  end

  alias_method :name, :to_s

  def transaction_changed
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  helper_method :referer

  def check
    if request.post?
      if supervisor_authenticated?
        current_user.temporary_role = User::Role.manager
        current_user.temporary_role_expires_at = Time.now + 1.hour
        current_user.save
        redirect_to params[:referer], notice: 'Override succesful.'
      else
        redirect_to root_path, notice: 'Override unsuccesful.'
      end
    else
      respond_to do |format|
        format.html
      end
    end
  end

  private

    def referer
      params[:referer]
    end

    def supervisor
      User.find_by(email: params[:supervisor_email])
    end

    def supervisor_authenticated?
      !!supervisor.try(:valid_password?, params[:supervisor_password])
    end

end

app/controllers/account/prefixes_controller.rb
class Account::PrefixesController < ApplicationController

  respond_to :json

  def index
    respond_with Account::Prefix.all
  end

  def show
    respond_with Account::Prefix.find(params[:id])
  end

  def create
    respond_with Account::Prefix.create(prefix_params)
  end

  def update
    respond_with Account::Prefix.update(params[:id], prefix_params)
  end

  def destroy
    respond_with Account::Prefix.destroy(params[:id])
  end

  private

    def prefix_params
      params.require(:prefix).permit(:name)
    end

end

app/controllers/account/transactions_controller.rb
class Account::TransactionsController < ApplicationController

  respond_to :json

  def index
    respond_with Account::Transaction.all
  end

  def show
    respond_with Account::Transaction.find(params[:id])
  end

  def create
    respond_with Account::Transaction.create(transaction_params)
  end

  def update
    respond_with Account::Transaction.update(params[:id], transaction_params)
  end

  def destroy
    respond_with Account::Transaction.destroy(params[:id])
  end

  private

    def transaction_params
      params.require(:transaction).permit(:credit, :debit, :value)
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  respond_to :json

  def index
    respond_with Account.all
  end

  def show
    respond_with Account.find(params[:id])
  end

  def create
    respond_with Account.create(account_params)
  end

  def update
    respond_with Account.update(params[:id], account_params)
  end

  def destroy
    respond_with Account.destroy(params[:id])
  end

  private

    def account_params
      params.require(:account).permit(:number)
    end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

  self.responder = ApplicationResponder

  respond_to :html

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
  end

  def redirect
    if user_signed_in?
      respond_to do |format|
        format.html
      end

    else
      redirect_to new_user_session_path
    end
  end

end

app/helpers/account/prefixes_helper.rb
module Account::PrefixesHelper
end

app/helpers/account/transactions_helper.rb
module Account::TransactionsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/bins/_bin.html.erb
<tr>
  <td><%= check_box_tag :row_selector %></td>
  <td><%= bin.name %></td>
  <td><%= bin.location %></td>
  <td><%= bin.bags %></td>
  <td><%= bin.actions %></td>
</tr>

app/views/bins/_form.html.erb
<%= form_for(bin) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.collection_select(:location_id, locations, :id, :name, {}, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label :bags %>
    <%= f.collection_select(:bag_ids, bags, :id, :name, {}, { multiple: 'multiple', class: 'textboxlist form-control' }) %>
  </div>
  
  <div class="actions">
    <%= f.submit :submit, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/bins/edit.html.erb
<h1>Editing bin</h1>

<%= render 'form' %>

<%= link_to 'Show', bin %> |
<%= link_to 'Back', bins_path %>

app/views/bins/index.html.erb
<div class="box box-solid box-warning">
  
  <div class="box-header">
    <h3 class="box-title">Bins</h3>
    <div class="box-tools">
      <div class="input-group">
        <%= form_tag(bins_path, method: :get, id: "search-form", remote: true, autocomplete: 'off') do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control input-sm pull-right" %>
        <% end %>

        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div>
  
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th><%= check_box_tag :table_selector %></th>
        <th><%= sortable :name, "ID" %></th>
        <th><%= sortable :location %></th>
        <th><%= sortable :bags, "Content" %></th>
        <th>Actions</th>
      </tr>
      
      <tbody id="table">
        <% bins.each do |bin| %>
          <%= render bin %>
        <% end %>
      </tbody>

      <tfoot>
        <tr>
          <th>Total</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tfoot>
    </table>
  </div>

</div>

<div class="tableFooter">
  <%= link_to "#{fa_icon 'square'} New bin".html_safe, '#', class: 'btn btn-flat btn-warning',
      data: { toggle: 'modal', target: '.new-bin'} %>

  <%= paginate bins %>
</div>

<%= render 'bins/modal/new' %>

app/views/bins/index.js.erb
$("#table").html("<%= escape_javascript(render("shared/ajax/table")) %>");

app/views/bins/label.html.erb
<script>
  var doc = new jsPDF('l', 'in', [3, 1]);
  
  doc.setFontSize(22);
  doc.text(1, 0.6, 'Bin : <%= bin.id %>');

  var imgData = '<%= j(to_data_url(bin.datamatrix)) %>'
  doc.addImage(imgData, 'PNG', 0.1, 0.1, 0.8, 0.8);
  
  doc.save('label.pdf');
</script>

app/views/bins/new.html.erb
<h1>New bin</h1>

<%= render 'form' %>

<%= link_to 'Back', bins_path %>

app/views/bins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bin_path(bin) %> |
<%= link_to 'Back', bins_path %>

app/views/inventory/lots/ajax/_table.html.erb
<% lots.each do |lot| %>
  <tr>
    <td><%= lot %></td>
    <td><%= lot.strain %></td>
    <td><%= lot.category %></td>
    <td><%= lot.current_weight %></td>
  </tr>
<% end %>

app/views/inventory/lots/home.html.erb
<div role="tabpanel">
  <% if Rails.env.development? %>
    <%= link_to 'Print PDF', inventory_lots_path( format: :pdf,
                                                  debug: 1,
                                                  direction: sort_direction,
                                                  sort: sort_column),
                                                  class: 'btn btn-primary pull-right' %>
  <% else %>
    <%= link_to 'Print PDF', inventory_lots_path( format: :pdf,
                                                  direction: sort_direction,
                                                  sort: sort_column),
                                                  class: 'btn btn-primary pull-right' %>
  <% end %>

  <%#= link_to 'Print Monthly Report', inventory_download_path, class: 'btn btn-primary pull-right'%>
  
  <%= render 'inventory/nav' %>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="lots">
      <%= form_for :filter, url: inventory_lots_path, remote: true, html: { id: 'filter-form' } do |f| %>
        <table class="table table-striped">
          <tr>
            <th class="col-md-2">
              <%= sortable :name, 'ID' %>
              <%= f.number_field :id, id: 'id-filter', class: 'filter form-control' %>
            </th>

            <th class="col-md-2">
              <%= sortable :strain %>
              <%= f.collection_select :strain, Strain.all, :id, :acronym,
                  { include_blank: true }, class: 'filter form-control', id: 'strain-filter' %>
            </th>

            <th class="col-md-2">
              <%= sortable :category %>
              <%= f.select :category, options_for_select(['Trim', 'Buds', 'Unprocessed']),
                  { include_blank: true }, class: 'filter form-control', id: 'category-filter' %>
            </th>

            <th class="col-md-2">
              <%= sortable :current_weight, 'Weight' %>
              <%= f.number_field :current_weight, id: 'current-weight-filter', class: 'filter form-control' %>
            </th>
          </tr>

          <tbody id="table-body">
            <%= render 'inventory/lots/ajax/table' %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/inventory/lots/home.js.erb
$("#table-body").html("<%= j(render("inventory/lots/ajax/table")) %>");

app/views/inventory/pdf/_plants.pdf.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Strain</th>
  </tr>

  <% plants.each do |plant| %>
    <tr>
      <td><%= plant.try(:to_s) if plant.present? %></td>
      <td><%= strain_for plant.try(:strain) if plant.present? %></td>
    </tr>
  <% end %>
</table>

app/views/inventory/pdf/report.pdf.erb
<%= render 'inventory/pdf/summary', weightable: Lot %><br>

<%= render 'inventory/pdf/summary', weightable: Container %><br>

<%= render 'inventory/pdf/summary', weightable: Bag %><br>

<%= render 'inventory/pdf/summary', weightable: Jar %><br>

<table class="table table-hover summary">
  <tr>
    <th class="col-md-10"><strong class="summary-total">Grand Total</strong></th>
    <th class="col-md-2 double-underlines text-right"><span class="summary-total right">
      <%= weight_for total_weight, '' %>
    </span></th>
  </tr>
</table>
  
<%= render 'inventory/pdf/plants' %>

<%= render 'inventory/pdf/jars' %>

<%= render 'inventory/pdf/lots' %>

<%= render 'inventory/pdf/containers' %>

<%= render 'inventory/pdf/bags' %>

app/views/inventory/plants/clones/home.html.erb
<div role="tabpanel">
  <% if Rails.env.development? %>
    <%= link_to 'Print PDF', inventory_plants_clones_path( format: :pdf,
                                                           debug: 1,
                                                           direction: sort_direction,
                                                           sort: sort_direction),
                 class: 'btn btn-primary pull-right' %>
  <% else %>
    <%= link_to 'Print PDF', inventory_plants_clones_path( format: :pdf,
                                                           direction: sort_direction,
                                                           sort: sort_column),
                 class: 'btn btn-primary pull-right' %>
  <% end %>

  <%#= link_to 'Print Monthly Report', inventory_download_path, class: 'btn btn-primary pull-right'%>
  
  <%= render 'inventory/nav' %>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="clones">
      <%= form_for :filter, url: inventory_plants_clones_path, remote: true, html: { id: 'filter-form' } do |f| %>
        <table class="table table-striped">
          <tr>
            <th class="col-md-3">
              <%= sortable :name, 'ID' %>
              <%= f.number_field :id, id: 'id-filter', class: 'filter form-control' %>
            </th>

            <th class="col-md-3">
              <%= sortable :strain_id %>
              <%= f.collection_select :strain_id, Strain.all, :id, :acronym,
                  { include_blank: true }, class: 'filter form-control', id: 'strain-filter' %>
            </th>

            <th class="col-md-3">
              <%= sortable :status_id %>
              <%= f.collection_select :status_id, Status.all, :id, :name,
                  { include_blank: true }, class: 'filter form-control', id: 'status-filter' %>
            </th>

            <th class="col-md-3">
              <%= sortable :format_id %>
              <%= f.collection_select :format_id, Format.all, :id, :name,
                  { include_blank: true }, class: 'filter form-control', id: 'format-filter' %>
            </th>
          </tr>

          <tbody id="table-body">
            <%= render 'inventory/plants/clones/ajax/table' %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/inventory/plants/clones/home.js.erb
$("#table-body").html("<%= j(render("inventory/plants/clones/ajax/table")) %>");

app/views/inventory/plants/mothers/ajax/_table.html.erb
<% mothers.each do |mother| %>
  <tr>
    <td><%= mother %></td>
    <td><%= strain_for mother.strain %></td>
    <td><%= mother.status %></td>
    <td><%= format_for mother.format %></td>
  </tr>
<% end %>

app/views/inventory/seeds/home.html.erb
<div role="tabpanel">
  <% if Rails.env.development? %>
    <%= link_to 'Print PDF', inventory_seeds_path( format: :pdf,
                                                    debug: 1,
                                                    direction: sort_direction,
                                                    sort: sort_column),
                                                    class: 'btn btn-primary pull-right' %>
  <% else %>
    <%= link_to 'Print PDF', inventory_seeds_path( format: :pdf,
                                                    direction: sort_direction,
                                                    sort: sort_column),
                                                    class: 'btn btn-primary pull-right' %>
  <% end %>

  <%#= link_to 'Print Monthly Report', inventory_download_path, class: 'btn btn-primary pull-right'%>
  
  <%= render 'inventory/nav' %>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="seeds">
      <%= form_for :filter, url: inventory_seeds_path, remote: true, html: { id: 'filter-form' } do |f| %>
        <table class="table table-striped">
          <tr>
            <th class="col-md-4">
              <%= sortable :name, 'ID' %>
              <%= f.number_field :name, id: 'id-filter', class: 'filter form-control' %>
            </th>

            <th class="col-md-4">
              <%= sortable :stock, 'Quantity' %>
              <%= f.number_field :stock, id: 'stock-filter', class: 'filter form-control' %>
            </th>
            
            <th class="col-md-4">
              <%= sortable :current_weight %>
              <%= f.number_field :current_weight, id: 'current-weight-filter', class: 'filter form-control' %>
            </th>
          </tr>

          <tbody id="table-body">
            <%= render 'inventory/seeds/ajax/table' %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/inventory/seeds/home.js.erb
$("#table-body").html("<%= j(render("inventory/seeds/ajax/table")) %>");

app/views/plants/modal/_new.html.erb
<div class="modal fade new-plant" tabindex="-1" role="dialog" aria-labelledby="New Plant" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <h3>Create a new plant</h3>
      <%= render 'plants/form' %>
    </div>
  </div>
</div>

app/views/seeds/ajax/_table.html.erb
<% seeds.each do |seed| %>
  <tr id="seed-<%= seed.id %>">
    <td></td>
    <td>
      <% if can? :show, Seed %>
        <%= link_to seed.try(:to_s), seed %>
      <% else %>
        <%= seed.try(:to_s) if seed.present? %>
      <% end %>
    </td>
    <td><%= seed.stock %></td>
    <td><%= seed.initial_stock %></td>
    <td><%= weight_for seed.try(:initial_weight) if seed.present? %></td>
    <td><%= weight_for seed.try(:current_weight) if seed.present? %></td>
    <td>
      <% if can? :label, Seed %>
      <%= link_to "Print Label", label_seed_path(seed), class: 'btn-sm btn-flat btn-primary' %>
      <% end %>

      <% if can? :reweight, Seed %>
      <%= link_to "#{fa_icon 'flask'} Reweight".html_safe, reweight_seed_path(seed),
          class: 'btn-sm btn-flat btn-danger reweight',
          data: { href: reweight_seed_path(seed) } %>
      <% end %>

      <% if can? :edit,  Seed %>
      <%= link_to "Edit".html_safe, edit_seed_path(seed), class: 'btn btn-flat btn-sm' %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :event %><br>
    <%= f.datetime_select :event, class: 'form-control', id: 'transaction-event'  %>
  </div>
  
  <div class="form-group">
    <%= f.label :source_id %>
    <%= f.text_field :source_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :source_type %>
    <%= f.select :source_type, options_for_select([
          [ 'Plant', 'Plant' ],
          [ 'Bag', 'Bag'],
          [ 'Jar', 'Jar'],
          [ 'Container', 'Container'],
          [ 'Harvest', 'Transactions::Harvest' ]
        ], selected: transaction.source_type), {}, class: 'form-control' %>
    <%= display_error_for transaction, :source_type %>
  </div>
  
  <div class="form-group">
    <%= f.label :target_id %>
    <%= f.text_field :target_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :target_type %>
    <%= f.select :target_type, options_for_select([
          [ 'Bag', 'Bag' ],
          [ 'Jar', 'Jar' ],
          [ 'Container', 'Container' ],
          [ 'Sent to Lab', 'Transactions::Lab' ],
          [ 'Destruction', 'Transactions::Destruction' ],
          [ 'Waste', 'Transactions::Waste' ],
          [ 'Water Loss', 'Transactions::WaterLoss' ]
        ], selected: transaction.target_type), {}, class: 'form-control' %>
    <%= display_error_for transaction, :target_type %>
  </div>
  
  <div class="form-group">
    <%= f.label :weight %>
    <%= f.text_field :weight, class: 'form-control' %>
  </div>

  <div class="input-group">
    <%= f.submit nil, class: 'btn btn-flat btn-primary' %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div class="box box-solid box-danger">
  <%= render 'shared/box_header', described: :transactions %>
  <%= render 'shared/box_table', described: :transactions %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= transaction.event %>
</p>

<p>
  <strong>Source:</strong>
  <%= transaction.source %>
</p>

<p>
  <strong>Target:</strong>
  <%= transaction.target %>
</p>

<p>
  <strong>Weight:</strong>
  <%= transaction.weight %>
</p>

<%= link_to 'Edit', edit_transaction_path(transaction) %> |
<%= link_to 'Back', transactions_path %>